spring:
  application:
    name: gateways
  config:
    import: configserver:http://localhost:7777
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:7777
    gateway:
      routes:
        - id: endpoints
          uri: http://localhost:10000
          predicates:
            - Path=/api/v1/**
