server:
  servlet:
    context-path: /
spring:
  application:
    name: services-loan
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:7777}
  profiles:
    active: default
  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:7777}

webclient:
  endpoints:
    base-url: http://${SERVICE_RATE_HOST:localhost}:${SERVICE_RATE_PORT:12000}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      cors:
        allowed-origins: true
      base-path: /actuator
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      services-loan:
        sliding-window-size: 100
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 5
        register-health-indicator: true
        sliding-window-type: count_based
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
