server:
  port: ${DISCOVERY_PORT:9999}
eureka:
  instance:
    prefer-ip-address: true
    #    hostname: ${DISCOVERY_HOST:localhost}
    homePageUrl: https://${eureka.instance.hostname}/
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:9999}/eureka/
spring:
  security:
    user:
      name: admin
      password: admin@123