server:
  port: 9999
eureka:
  instance:
    hostname: localhost
    homePageUrl: https://${eureka.instance.hostname}/
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
spring:
  security:
    user:
      name: admin
      password: admin@123