server:
  port: ${ENDPOINTS_PORT:10000}
eureka:
  instance:
    prefer-ip-address: true
#    hostname: ${ENDPOINTS_PORT:localhost}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:9999}/eureka/
spring:
  security:
    user:
      name: system
      roles: system
      password: system!123
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/sample
    username: root
    password: QWEqwe123@
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: NDEzRjQ0Mjg0NzJCNEI2MjUwNjU1MzY4NTY2RDU5NzAzMzczMzY3NjM5NzkyNDQyMjY0NTI5NDg0MDRENjM1MQ

openapi:
  service:
    title: price-service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://${ENDPOINTS_PORT:localhost}:${ENDPOINTS_PORT:10000} #api gateway url
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    enabled: true
    #  http://localhost:10000/swagger-ui/index.html
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    #    Selection dropdown definitions
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        display-name: API Gateway Service
#      - url: /product-service/v3/api-docs
#        name: Product Service
#        display-name: Product Service
#      - url: /price-service/v3/api-docs
#        name: Price Service
#        display-name: Price Service