server:
  port: 10001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: endpoints
          uri: http://localhost:10000
          predicates:
            - Path=/api/v1/**
