server:
  port: ${SERVICE_LOAN_PORT:13000}
eureka:
  instance:
    prefer-ip-address: true
  #    hostname: ${ENDPOINTS_PORT:localhost}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:9999}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info # Endpoint IDs that should be included or '*' for all.
      base-path: /actuator

spring:
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/sample
    username: root
    password: QWEqwe123@
    driver-class-name: com.mysql.cj.jdbc.Driver