server:
  servlet:
    context-path: /
spring:
  application:
    name: endpoints
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:7777}
  profiles:
    active: default
  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:7777}
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp