version: "3.9"
services:
  #######################################
  # Postgres: Kong Database
  # ! Postgres 11.16 is the latest version that supported by Konga v0.14.9
  #######################################
  postgres:
    image: postgres:11.16
    restart: always
    hostname: kong-database
    container_name: postgres
    environment:
      POSTGRES_DB: "kong"
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
    networks:
      - default
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 5s
      timeout: 5s
      retries: 5
  #######################################
  # Kong database migration
  #######################################
  kong-bootstrap:
    image: kong:3.4.2
    restart: on-failure
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    networks:
      - default
    depends_on:
      - postgres
    environment:
      KONG_PG_PASSWORD: "kong"
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
    command: "kong migrations bootstrap"
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:3.4.2
    restart: always
    hostname: kong
    container_name: kong
    networks:
      - default
    depends_on:
      - kong-bootstrap
      - postgres
    environment:
      KONG_PG_USER: "kong"
      KONG_PG_DATABASE: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    command: "kong start"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nginx:8001" ]
      interval: 5s
      timeout: 2s
      retries: 15
    #   remove the tailing protocol "tcp/utp" from the port declaration to allow konga to connect
    #    ports:
    #      - "8000:8000"
    #      - "8001:8001"
    #      - "8002:8002"
    #      - "8003:8003"
    #      - "8004:8004"
    #      - "8443:8443"
    #      - "8444:8444"
    #      - "8445:8445"
    expose:
      - "8001"  # admin endpoint
      - "8000"  # proxy endpoint
  #######################################
  # Konga database migration
  #######################################
  konga-bootstrap:
    image: pantsel/konga:0.14.9
    container_name: konga-bootstrap
    restart: on-failure
    networks:
      - default
    depends_on:
      - postgres
    links:
      - postgres
    platform: "linux/amd64"
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/kong"
  #######################################
  # Konga: GUI of KONG Admin API
  #######################################
  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: always
    networks:
      - default
    depends_on:
      - konga-bootstrap
    platform: "linux/amd64"
    expose:
      - "1337"

  #######################################
  # NGinX: Load Balancer
  #######################################
  ngix:
    image: nginx:latest
    container_name: ngix
    networks:
      - default
    restart: always
    depends_on:
      - kong
      - konga
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
      - "8001:8001"
      - "1337:1337"

networks:
  default:
    name: kong-net