version: "3.9"
services:
  #######################################
  # Postgres: Kong Database
  # ! Postgres v11.16 is the latest version that supported by Konga v0.14.9
  #######################################
  postgres:
    image: postgres:11.16
    restart: always
    hostname: kong-database
    container_name: postgres
    environment:
      POSTGRES_DB: "kong"
      POSTGRES_USER: "kong"
      POSTGRES_PASSWORD: "kong"
    networks:
      - default
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "kong" ]
      interval: 5s
      timeout: 5s
      retries: 5
  #######################################
  # Kong database migration
  #######################################
  kong-bootstrap:
    image: kong:3.4.2
    restart: on-failure
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    networks:
      - default
    depends_on:
      - postgres
    environment:
      KONG_PG_PASSWORD: "kong"
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
    command: "kong migrations bootstrap"
  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:3.4.2
    restart: always
    hostname: kong
    container_name: kong
    networks:
      - default
    depends_on:
      - kong-bootstrap
      - postgres
    environment:
      KONG_PG_USER: "kong"
      KONG_PG_DATABASE: "kong"
      KONG_PG_PASSWORD: "kong"
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN_SSL: 0.0.0.0:8444
    command: "kong start; 
    curl --location --request POST 'http://localhost:8001/services/' \ --header 'Content-Type: application/json' \ --data-raw '{ \"name\": \"admin-api\", \"host\": \"localhost\", \"port\": 8001 }';
    curl --location --request POST 'http://localhost:8001/services/{service_id|service_name}/routes' \ --header 'Content-Type: application/json' \ --data-raw '{ \"paths\": [\"/admin-api\"] }'
    curl localhost:8000/admin-api/;
    curl -X POST http://localhost:8001/services/{service_id|service_name}/plugins \ --data \"name=key-auth\"
    "
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nginx:8001" ]
      interval: 5s
      timeout: 2s
      retries: 15
    #   remove the tailing protocol "tcp/utp" from the port declaration to allow konga to connect
    #    ports:
    #      - "8000:8000"
    #      - "8001:8001"
    #      - "8002:8002"
    #      - "8003:8003"
    #      - "8004:8004"
    #      - "8443:8443"
    #      - "8444:8444"
    #      - "8445:8445"
    expose:
      - "8001"  # admin endpoint
      - "8000"  # proxy endpoint
  #######################################
  # Konga database migration
  #######################################
  konga-bootstrap:
    image: pantsel/konga:0.14.9
    container_name: konga-bootstrap
    restart: on-failure
    networks:
      - default
    depends_on:
      - postgres
    links:
      - postgres
    platform: "linux/amd64"
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/kong;
    curl --location --request POST 'http://localhost:8001/consumers/' \ --form 'username=konga' \ --form 'custom_id={{custom_id}}'
    curl --location --request POST ‘http://localhost:8001/consumers/{{consumer_id}}/key-auth'"
  #######################################
  # Konga: GUI of KONG Admin API
  #######################################
  konga:
    image: pantsel/konga:0.14.9
    container_name: konga
    restart: always
    networks:
      - default
    depends_on:
      - konga-bootstrap
    platform: "linux/amd64"
    expose:
      - "1337"

  #############################################
  # Digital System : build block
  #############################################
  # ---- Spring cloud MySql
  mysql:
    image: mysql:8.0
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - digital_system.env
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    # seeding data in case of needed
    #      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=QWEqwe123@
      # jdbc:mysql://localhost:3306/lhtk
      # connection string : jdbc:mysql://root:QWEqwe123@localhost:3306/sample
  # ---- config server
  config:
    image: pisethraingsey/configuration:1.0-SNAPSHOT
    container_name: config
    restart: always
    env_file:
      - digital_system.env
    networks:
      - default
    expose:
      - "7777"
  # ---- discovery
  discovery:
    image: pisethraingsey/discovery:1.0-SNAPSHOT
    container_name: discovery
    restart: no
    env_file:
      - digital_system.env
    depends_on:
      config:
        condition: service_started
    networks:
      - default
    ports:
      - "9999:9999"
  # ---- endpoints
  endpoints:
    image: pisethraingsey/endpoints:1.0-SNAPSHOT
    container_name: endpoints
    restart: no
    env_file:
      - digital_system.env
    depends_on:
      config:
        condition: service_started
      mysql:
        condition: service_started
    networks:
      - default
    ports:
      - "10000:10000"

  # ---- applications
  applications:
    image: pisethraingsey/applications:1.0-SNAPSHOT
    container_name: applications
    restart: no
    env_file:
      - digital_system.env
    depends_on:
      config:
        condition: service_started
      mysql:
        condition: service_started
    networks:
      - default
    ports:
      - "11000:11000"

  #######################################
  # NGinX: Load Balancer
  #######################################
  nginx:
    image: nginx:1.25-alpine-slim
    container_name: nginx
    restart: always
    depends_on:
      - kong
      - konga
    networks:
      - default
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
      - "8001:8001"
      - "1337:1337"
      - "7777:7777"

networks:
  default:
    name: kong-net

volumes:
  mysqldb:
    driver: local